
--
-- Create model Code
--
CREATE TABLE "MAINAPP_CODE" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "INFORMATION" NVARCHAR2(20) NULL);
--
-- Create model Customer
--
CREATE TABLE "MAINAPP_CUSTOMER" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "NAME" NVARCHAR2(25) NULL, "MILEAGE" NUMBER(10, 0) NOT NULL, "GENDER" NUMBER(4, 0) NULL, "BIRTHDAY" DATE NULL, "CONTACT" NVARCHAR2(20) NULL);
--
-- Create model Customer_refund
--
CREATE TABLE "MAINAPP_CUSTOMER_REFUND" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "REFUND_TIMESTAMP" TIMESTAMP NOT NULL, "REFUND_REASON_CODE" NUMBER(4, 0) NOT NULL);
--
-- Create model Employee
--
CREATE TABLE "MAINAPP_EMPLOYEE" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "NAME" NVARCHAR2(25) NULL, "DAYTIME_HOURPAY" NUMBER(10, 0) NULL, "NIGHTTIME_HOURPAY" NUMBER(10, 0) NULL, "EMPLOYED_DATE" DATE NOT NULL, "FIRE_DATE" DATE NULL, "CONTACT" NVARCHAR2(20) NULL, "POSITION_CODE" NUMBER(4, 0) NOT NULL);
--
-- Create model Franchise_store_rcpt
--
CREATE TABLE "MAINAPP_FRANCHISE_STORE_RCPT" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "RCPT_DATE" DATE NOT NULL, "RCPT_AMOUNT" NUMBER(10, 0) NOT NULL);
--
-- Create model Maintenance_cost
--
CREATE TABLE "MAINAPP_MAINTENANCE_COST" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "MAINTENANCE_COST_CODE" NUMBER(4, 0) NOT NULL, "AMOUNT" NUMBER(10, 0) NOT NULL, "PROCESS_DATE" DATE NOT NULL, "ETC" NVARCHAR2(80) NULL, "STOREOWNER_CHECK" NVARCHAR2(1) NULL, "EMPLOYEE_ID" NUMBER(11) NULL);
--
-- Create model Order
--
CREATE TABLE "MAINAPP_ORDER" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "ORDER_TIMESTAMP" TIMESTAMP NOT NULL, "COMPLETE_TIMESTAMP" TIMESTAMP NULL, "PROCESS_CODE" NUMBER(4, 0) NOT NULL);
--
-- Create model Order_list
--
CREATE TABLE "MAINAPP_ORDER_LIST" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "QUANTITY" NUMBER(6, 0) NOT NULL, "SENT_TIMESTAMP" TIMESTAMP NULL, "ARRIVAL_TIMESTAMP" TIMESTAMP NULL, "PROCESS_CODE" NUMBER(4, 0) NOT NULL);
--
-- Create model Product
--
CREATE TABLE "MAINAPP_PRODUCT" ("BARCODE" NUMBER(13, 0) NOT NULL PRIMARY KEY, "NAME" NVARCHAR2(50) NULL, "SUPPLY_PRICE" NUMBER(10, 0) NOT NULL, "UNIT_PRICE" NUMBER(10, 0) NOT NULL, "CATEGORY_A" NUMBER(4, 0) NOT NULL, "CATEGORY_B" NUMBER(4, 0) NOT NULL, "EXPLAIN" NVARCHAR2(80) NULL, "PICTURE_FILE_PATH" NVARCHAR2(80) NULL);
--
-- Create model Receipt
--
CREATE TABLE "MAINAPP_RECEIPT" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "TRADE_TIMESTAMP" TIMESTAMP NOT NULL, "PAYMENT_METHOD_CODE" NUMBER(4, 0) NOT NULL, "PAYMENT_INFORMATION" NVARCHAR2(30) NULL, "CUSTOMER_ID" NUMBER(11) NULL, "EMPLOYEE_ID" NUMBER(11) NOT NULL);
--
-- Create model Setting
--
CREATE TABLE "MAINAPP_SETTING" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "NAME" NVARCHAR2(20) NULL, "VALUE" NUMBER(10, 0) NOT NULL);
--
-- Create model Stock
--
CREATE TABLE "MAINAPP_STOCK" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "DISPLAY_LOCATION_CODE" NUMBER(4, 0) NOT NULL, "QUANTITY" NUMBER(6, 0) NOT NULL, "BARCODE_ID" NUMBER(13, 0) NOT NULL);
--
-- Create model Store
--
CREATE TABLE "MAINAPP_STORE" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "ADDRESS" NVARCHAR2(80) NULL, "CONTACT" NVARCHAR2(20) NULL, "STORE_PAY" DOUBLE PRECISION NOT NULL, "STORE_CODE" NUMBER(4, 0) NOT NULL);
--
-- Create model Store_refund
--
CREATE TABLE "MAINAPP_STORE_REFUND" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "QUANTITY" NUMBER(6, 0) NOT NULL, "REFUND_TIMESTAMP" TIMESTAMP NOT NULL, "REFUND_REASON_CODE" NUMBER(4, 0) NOT NULL, "PROCESS_CODE" NUMBER(4, 0) NOT NULL, "BARCODE" NUMBER(13, 0) NOT NULL, "STORE_ID" NUMBER(11) NOT NULL);
--
-- Create model Supplier
--
CREATE TABLE "MAINAPP_SUPPLIER" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "NAME" NVARCHAR2(25) NULL, "CONTACT" NVARCHAR2(20) NULL, "EMAIL" NVARCHAR2(40) NULL);
--
-- Create model Trade_list
--
CREATE TABLE "MAINAPP_TRADE_LIST" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "QUANTITY" NUMBER(6, 0) NOT NULL, "IS_REFUND" NVARCHAR2(1) NULL, "BARCODE" NUMBER(13, 0) NOT NULL, "RECEIPT_ID" NUMBER(11) NOT NULL);
--
-- Create model User
--
CREATE TABLE "MAINAPP_USER" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "USER_ID" NVARCHAR2(50) NULL, "PASSWORD" NVARCHAR2(200) NULL, "STORE_ID" NUMBER(11) NULL);
--
-- Create model Work_list
--
CREATE TABLE "MAINAPP_WORK_LIST" ("ID" NUMBER(11) NOT NULL PRIMARY KEY, "WORKSTART_TIMESTAMP" TIMESTAMP NOT NULL, "WORKEND_TIMESTAMP" TIMESTAMP NOT NULL, "STOREOWNER_CHECK" NVARCHAR2(1) NULL, "EMPLOYEE_ID" NUMBER(11) NOT NULL);
--
-- Add field store_id to stock
--
ALTER TABLE "MAINAPP_STOCK" ADD "STORE_ID" NUMBER(11) NOT NULL;
--
-- Add field store_id to receipt
--
ALTER TABLE "MAINAPP_RECEIPT" ADD "STORE_ID" NUMBER(11) NOT NULL;
--
-- Add field supplier_id to product
--
ALTER TABLE "MAINAPP_PRODUCT" ADD "SUPPLIER_ID" NUMBER(11) NOT NULL;
--
-- Add field barcode to order_list
--
ALTER TABLE "MAINAPP_ORDER_LIST" ADD "BARCODE" NUMBER(13, 0) NOT NULL;
--
-- Add field order_id to order_list
--
ALTER TABLE "MAINAPP_ORDER_LIST" ADD "ORDER_ID_ID" NUMBER(11) NOT NULL;
--
-- Add field store_id to order
--
ALTER TABLE "MAINAPP_ORDER" ADD "STORE_ID" NUMBER(11) NOT NULL;
--
-- Add field store_id to maintenance_cost
--
ALTER TABLE "MAINAPP_MAINTENANCE_COST" ADD "STORE_ID" NUMBER(11) NOT NULL;
--
-- Add field store_id to franchise_store_rcpt
--
ALTER TABLE "MAINAPP_FRANCHISE_STORE_RCPT" ADD "STORE_ID" NUMBER(11) NOT NULL;
--
-- Add field store_id to employee
--
ALTER TABLE "MAINAPP_EMPLOYEE" ADD "STORE_ID" NUMBER(11) NOT NULL;
--
-- Add field trade_list_id to customer_refund
--
ALTER TABLE "MAINAPP_CUSTOMER_REFUND" ADD "TRADE_LIST_ID" NUMBER(11) NOT NULL;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_CODE_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_CODE_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_CODE_TR"
BEFORE INSERT ON "MAINAPP_CODE"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_CODE_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_CUSTOMER_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_CUSTOMER_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_CUSTOMER_TR"
BEFORE INSERT ON "MAINAPP_CUSTOMER"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_CUSTOMER_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_CUSTOMER_REFUND_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_CUSTOMER_REFUND_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_CUSTOMER_REFUND_TR"
BEFORE INSERT ON "MAINAPP_CUSTOMER_REFUND"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_CUSTOMER_REFUND_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_EMPLOYEE_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_EMPLOYEE_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_EMPLOYEE_TR"
BEFORE INSERT ON "MAINAPP_EMPLOYEE"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_EMPLOYEE_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_FRANCHISE_STORE3DF9_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_FRANCHISE_STORE3DF9_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_FRANCHISE_STORE3DF9_TR"
BEFORE INSERT ON "MAINAPP_FRANCHISE_STORE_RCPT"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_FRANCHISE_STORE3DF9_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_MAINTENANCE_COST_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_MAINTENANCE_COST_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_MAINTENANCE_COST_TR"
BEFORE INSERT ON "MAINAPP_MAINTENANCE_COST"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_MAINTENANCE_COST_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;
ALTER TABLE "MAINAPP_MAINTENANCE_COST" ADD CONSTRAINT "MAINAPP_M_EMPLOYEE__F13CA2EA_F" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "MAINAPP_EMPLOYEE" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_MA_EMPLOYEE_I_F13CA2EA" ON "MAINAPP_MAINTENANCE_COST" ("EMPLOYEE_ID");

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_ORDER_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_ORDER_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_ORDER_TR"
BEFORE INSERT ON "MAINAPP_ORDER"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_ORDER_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_ORDER_LIST_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_ORDER_LIST_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_ORDER_LIST_TR"
BEFORE INSERT ON "MAINAPP_ORDER_LIST"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_ORDER_LIST_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_RECEIPT_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_RECEIPT_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_RECEIPT_TR"
BEFORE INSERT ON "MAINAPP_RECEIPT"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_RECEIPT_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;
ALTER TABLE "MAINAPP_RECEIPT" ADD CONSTRAINT "MAINAPP_R_CUSTOMER__721BA02B_F" FOREIGN KEY ("CUSTOMER_ID") REFERENCES "MAINAPP_CUSTOMER" ("ID") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "MAINAPP_RECEIPT" ADD CONSTRAINT "MAINAPP_R_EMPLOYEE__09A93FD5_F" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "MAINAPP_EMPLOYEE" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_RE_CUSTOMER_I_721BA02B" ON "MAINAPP_RECEIPT" ("CUSTOMER_ID");
CREATE INDEX "MAINAPP_RE_EMPLOYEE_I_09A93FD5" ON "MAINAPP_RECEIPT" ("EMPLOYEE_ID");

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_SETTING_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_SETTING_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_SETTING_TR"
BEFORE INSERT ON "MAINAPP_SETTING"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_SETTING_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_STOCK_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_STOCK_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_STOCK_TR"
BEFORE INSERT ON "MAINAPP_STOCK"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_STOCK_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;
ALTER TABLE "MAINAPP_STOCK" ADD CONSTRAINT "MAINAPP_S_BARCODE_I_2E40C6C2_F" FOREIGN KEY ("BARCODE_ID") REFERENCES "MAINAPP_PRODUCT" ("BARCODE") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_ST_BARCODE_ID_2E40C6C2" ON "MAINAPP_STOCK" ("BARCODE_ID");

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_STORE_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_STORE_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_STORE_TR"
BEFORE INSERT ON "MAINAPP_STORE"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_STORE_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_STORE_REFUND_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_STORE_REFUND_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_STORE_REFUND_TR"
BEFORE INSERT ON "MAINAPP_STORE_REFUND"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_STORE_REFUND_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;
ALTER TABLE "MAINAPP_STORE_REFUND" ADD CONSTRAINT "MAINAPP_S_BARCODE_19D7189F_F" FOREIGN KEY ("BARCODE") REFERENCES "MAINAPP_PRODUCT" ("BARCODE") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "MAINAPP_STORE_REFUND" ADD CONSTRAINT "MAINAPP_S_STORE_ID_A75D3323_F" FOREIGN KEY ("STORE_ID") REFERENCES "MAINAPP_STORE" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_ST_BARCODE_19D7189F" ON "MAINAPP_STORE_REFUND" ("BARCODE");
CREATE INDEX "MAINAPP_ST_STORE_ID_A75D3323" ON "MAINAPP_STORE_REFUND" ("STORE_ID");

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_SUPPLIER_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_SUPPLIER_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_SUPPLIER_TR"
BEFORE INSERT ON "MAINAPP_SUPPLIER"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_SUPPLIER_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_TRADE_LIST_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_TRADE_LIST_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_TRADE_LIST_TR"
BEFORE INSERT ON "MAINAPP_TRADE_LIST"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_TRADE_LIST_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;
ALTER TABLE "MAINAPP_TRADE_LIST" ADD CONSTRAINT "MAINAPP_T_BARCODE_D1ED480F_F" FOREIGN KEY ("BARCODE") REFERENCES "MAINAPP_PRODUCT" ("BARCODE") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "MAINAPP_TRADE_LIST" ADD CONSTRAINT "MAINAPP_T_RECEIPT_I_5AFEB3C0_F" FOREIGN KEY ("RECEIPT_ID") REFERENCES "MAINAPP_RECEIPT" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_TR_BARCODE_D1ED480F" ON "MAINAPP_TRADE_LIST" ("BARCODE");
CREATE INDEX "MAINAPP_TR_RECEIPT_ID_5AFEB3C0" ON "MAINAPP_TRADE_LIST" ("RECEIPT_ID");

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_USER_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_USER_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_USER_TR"
BEFORE INSERT ON "MAINAPP_USER"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_USER_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;
ALTER TABLE "MAINAPP_USER" ADD CONSTRAINT "MAINAPP_U_STORE_ID_C99F6DE8_F" FOREIGN KEY ("STORE_ID") REFERENCES "MAINAPP_STORE" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_USER_STORE_ID_C99F6DE8" ON "MAINAPP_USER" ("STORE_ID");

DECLARE
    i INTEGER;
BEGIN
    SELECT COUNT(1) INTO i FROM USER_SEQUENCES
        WHERE SEQUENCE_NAME = 'MAINAPP_WORK_LIST_SQ';
    IF i = 0 THEN
        EXECUTE IMMEDIATE 'CREATE SEQUENCE "MAINAPP_WORK_LIST_SQ"';
    END IF;
END;
/;

CREATE OR REPLACE TRIGGER "MAINAPP_WORK_LIST_TR"
BEFORE INSERT ON "MAINAPP_WORK_LIST"
FOR EACH ROW
WHEN (new."ID" IS NULL)
    BEGIN
        SELECT "MAINAPP_WORK_LIST_SQ".nextval
        INTO :new."ID" FROM dual;
    END;
/;
ALTER TABLE "MAINAPP_WORK_LIST" ADD CONSTRAINT "MAINAPP_W_EMPLOYEE__6C4293D6_F" FOREIGN KEY ("EMPLOYEE_ID") REFERENCES "MAINAPP_EMPLOYEE" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_WO_EMPLOYEE_I_6C4293D6" ON "MAINAPP_WORK_LIST" ("EMPLOYEE_ID");
CREATE INDEX "MAINAPP_ST_STORE_ID_A102F9BF" ON "MAINAPP_STOCK" ("STORE_ID");
ALTER TABLE "MAINAPP_STOCK" ADD CONSTRAINT "MAINAPP_S_STORE_ID_A102F9BF_F" FOREIGN KEY ("STORE_ID") REFERENCES "MAINAPP_STORE" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_RE_STORE_ID_E9DBF15A" ON "MAINAPP_RECEIPT" ("STORE_ID");
ALTER TABLE "MAINAPP_RECEIPT" ADD CONSTRAINT "MAINAPP_R_STORE_ID_E9DBF15A_F" FOREIGN KEY ("STORE_ID") REFERENCES "MAINAPP_STORE" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_PR_SUPPLIER_I_F300BDFE" ON "MAINAPP_PRODUCT" ("SUPPLIER_ID");
ALTER TABLE "MAINAPP_PRODUCT" ADD CONSTRAINT "MAINAPP_P_SUPPLIER__F300BDFE_F" FOREIGN KEY ("SUPPLIER_ID") REFERENCES "MAINAPP_SUPPLIER" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_OR_BARCODE_B46530E6" ON "MAINAPP_ORDER_LIST" ("BARCODE");
ALTER TABLE "MAINAPP_ORDER_LIST" ADD CONSTRAINT "MAINAPP_O_BARCODE_B46530E6_F" FOREIGN KEY ("BARCODE") REFERENCES "MAINAPP_PRODUCT" ("BARCODE") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_OR_ORDER_ID_I_EBCBDDE0" ON "MAINAPP_ORDER_LIST" ("ORDER_ID_ID");
ALTER TABLE "MAINAPP_ORDER_LIST" ADD CONSTRAINT "MAINAPP_O_ORDER_ID__EBCBDDE0_F" FOREIGN KEY ("ORDER_ID_ID") REFERENCES "MAINAPP_ORDER" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_OR_STORE_ID_1F74B00C" ON "MAINAPP_ORDER" ("STORE_ID");
ALTER TABLE "MAINAPP_ORDER" ADD CONSTRAINT "MAINAPP_O_STORE_ID_1F74B00C_F" FOREIGN KEY ("STORE_ID") REFERENCES "MAINAPP_STORE" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_MA_STORE_ID_41601059" ON "MAINAPP_MAINTENANCE_COST" ("STORE_ID");
ALTER TABLE "MAINAPP_MAINTENANCE_COST" ADD CONSTRAINT "MAINAPP_M_STORE_ID_41601059_F" FOREIGN KEY ("STORE_ID") REFERENCES "MAINAPP_STORE" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_FR_STORE_ID_2D27F26F" ON "MAINAPP_FRANCHISE_STORE_RCPT" ("STORE_ID");
ALTER TABLE "MAINAPP_FRANCHISE_STORE_RCPT" ADD CONSTRAINT "MAINAPP_F_STORE_ID_2D27F26F_F" FOREIGN KEY ("STORE_ID") REFERENCES "MAINAPP_STORE" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_EM_STORE_ID_E9A24D94" ON "MAINAPP_EMPLOYEE" ("STORE_ID");
ALTER TABLE "MAINAPP_EMPLOYEE" ADD CONSTRAINT "MAINAPP_E_STORE_ID_E9A24D94_F" FOREIGN KEY ("STORE_ID") REFERENCES "MAINAPP_STORE" ("ID") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "MAINAPP_CU_TRADE_LIST_323C822D" ON "MAINAPP_CUSTOMER_REFUND" ("TRADE_LIST_ID");
ALTER TABLE "MAINAPP_CUSTOMER_REFUND" ADD CONSTRAINT "MAINAPP_C_TRADE_LIS_323C822D_F" FOREIGN KEY ("TRADE_LIST_ID") REFERENCES "MAINAPP_TRADE_LIST" ("ID") DEFERRABLE INITIALLY DEFERRED;
COMMIT;
