# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-11 08:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='employee_id',
        ),
        migrations.AddField(
            model_name='user',
            name='emp_pos_code',
            field=models.DecimalField(choices=[(0, '지점장/본점장'), (1, '직원')], decimal_places=0, default=0, max_digits=1),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.DecimalField(choices=[(None, '미선택'), (1, '남'), (2, '여')], decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='customer_refund',
            name='refund_reason_code',
            field=models.DecimalField(choices=[(0, '일반반품'), (1, '본사리콜'), (2, '불량품'), (-1, '유통기한')], decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_code',
            field=models.DecimalField(choices=[(0, '점주'), (1, '매니저'), (2, '직원')], decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='maintenance_cost',
            name='maintenance_cost_code',
            field=models.DecimalField(choices=[(0, '기타'), (1, '세금/유지비'), (2, '월세'), (3, '직원과실'), (4, '절도')], decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='maintenance_cost',
            name='storeowner_check',
            field=models.CharField(choices=[('N', '미확인'), ('Y', '확인')], default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='process_code',
            field=models.DecimalField(choices=[(0, '처리대기'), (1, '배송시작'), (2, '배송완료'), (3, '처리완료'), (-1, '주문취소')], decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='order_list',
            name='process_code',
            field=models.DecimalField(choices=[(0, '처리대기'), (1, '배송시작'), (2, '배송완료'), (3, '처리완료'), (-1, '주문취소'), (-2, '처리불가')], decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_a',
            field=models.DecimalField(choices=[(0, '기타'), (1, '신선식품'), (2, '식품'), (3, '주류'), (4, '생활용품'), (5, '담배')], decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_b',
            field=models.DecimalField(choices=[(0, '일반판매'), (1, '기간한정판매'), (2, '할인행사판매')], decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method_code',
            field=models.DecimalField(choices=[(0, '현금'), (1, '체크/신용카드'), (2, '편의점상품권'), (3, '마일리지'), (4, '간편결제앱')], decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='stock',
            name='display_location_code',
            field=models.DecimalField(choices=[(0, '진열'), (1, '창고'), (2, '매장외부')], decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_code',
            field=models.DecimalField(choices=[(1, '개점'), (2, '폐점')], decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='store_refund',
            name='process_code',
            field=models.DecimalField(choices=[(0, '반품대기'), (1, '회수완료'), (2, '반품불가'), (-1, '자체폐기')], decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='store_refund',
            name='refund_reason_code',
            field=models.DecimalField(choices=[(0, '일반반품'), (1, '본사리콜'), (2, '불량품'), (-1, '유통기한폐기')], decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='work_list',
            name='storeowner_check',
            field=models.CharField(choices=[('N', '미확인'), ('Y', '확인')], default='N', max_length=1),
        ),
    ]
