# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('information', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('mileage', models.IntegerField(default=None)),
                ('gender', models.IntegerField(default=None)),
                ('birthday', models.DateField()),
                ('contact', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customerrefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_date', models.DateTimeField()),
                ('refund_reason_code', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('daytime_hourpay', models.IntegerField(default=None)),
                ('nighttime_hourpay', models.IntegerField(default=None)),
                ('employed_date', models.DateField()),
                ('fire_date', models.DateField()),
                ('contact', models.CharField(max_length=20)),
                ('position_code', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_code', models.IntegerField(default=None)),
                ('amount', models.IntegerField(default=None)),
                ('process_date', models.DateField()),
                ('information', models.TextField(default=None)),
                ('storeowner_check', models.CharField(max_length=1)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_timestamp', models.DateTimeField(default=None)),
                ('complete_timestamp', models.DateTimeField(default=None)),
                ('process_code', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Orderlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=None)),
                ('sent_timestamp', models.DateTimeField()),
                ('arrival_timestamp', models.DateTimeField()),
                ('process_code', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_timestamp', models.DateTimeField()),
                ('payment_method_code', models.IntegerField(default=None)),
                ('payment_information', models.CharField(max_length=30)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Customer')),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('value', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_code', models.IntegerField(default=None)),
                ('quantity', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=80)),
                ('contact', models.CharField(max_length=20)),
                ('store_pay', models.FloatField(default=None)),
                ('store_code', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Storercpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcpt_timestamp', models.DateTimeField()),
                ('amount', models.IntegerField(default=None)),
                ('store_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store')),
            ],
        ),
        migrations.CreateModel(
            name='Storerefund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=None)),
                ('refund_timestamp', models.IntegerField(default=None)),
                ('refund_reason_code', models.IntegerField(default=None)),
                ('process_code', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('contact', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tradelist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=None)),
                ('is_refund', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Worklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workstart_timestamp', models.DateTimeField()),
                ('workend_timestamp', models.DateTimeField()),
                ('storeowner_check', models.CharField(max_length=1)),
                ('emp_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Employee')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='id',
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='product',
            name='category_a',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='category_b',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='img_path',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='information',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='supply_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='userId',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='tradelist',
            name='barcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product'),
        ),
        migrations.AddField(
            model_name='tradelist',
            name='receipt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Receipt'),
        ),
        migrations.AddField(
            model_name='storerefund',
            name='barcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product'),
        ),
        migrations.AddField(
            model_name='storerefund',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
        ),
        migrations.AddField(
            model_name='stock',
            name='barcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product'),
        ),
        migrations.AddField(
            model_name='stock',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='barcode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
        ),
        migrations.AddField(
            model_name='employee',
            name='store_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
        ),
        migrations.AddField(
            model_name='customerrefund',
            name='receipt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Receipt'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Supplier'),
        ),
    ]
