# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-08 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20190608_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='work_list',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', default=2, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
            preserve_default=False,
        ),
    ]
