# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-28 08:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20190528_0828'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerrefund',
            old_name='receipt_id',
            new_name='receipt',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='emp_id',
            new_name='emp',
        ),
        migrations.RenameField(
            model_name='maintenance',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='orderlist',
            old_name='order_id',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='supplier_id',
            new_name='supplier',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='emp_id',
            new_name='emp',
        ),
        migrations.RenameField(
            model_name='receipt',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='storercpt',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='storerefund',
            old_name='store_id',
            new_name='store',
        ),
        migrations.RenameField(
            model_name='tradelist',
            old_name='receipt_id',
            new_name='receipt',
        ),
        migrations.RenameField(
            model_name='worklist',
            old_name='emp_id',
            new_name='emp',
        ),
    ]
