# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-08 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_work_list_store_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work_list',
            name='store_id',
        ),
    ]
