# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_remove_product_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_timestamp', models.DateTimeField()),
                ('refund_reason_code', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Franchise_store_rcpt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcpt_date', models.DateField()),
                ('rcpt_amount', models.DecimalField(decimal_places=0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Maintenance_cost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_cost_code', models.DecimalField(decimal_places=0, max_digits=4)),
                ('amount', models.DecimalField(decimal_places=0, max_digits=10)),
                ('process_date', models.DateField()),
                ('etc', models.CharField(max_length=80, null=True)),
                ('storeowner_check', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Order_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=6)),
                ('sent_timestamp', models.DateTimeField(null=True)),
                ('arrival_timestamp', models.DateTimeField(null=True)),
                ('process_code', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Store_refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=6)),
                ('refund_timestamp', models.DateTimeField()),
                ('refund_reason_code', models.DecimalField(decimal_places=0, max_digits=4)),
                ('process_code', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Trade_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=0, max_digits=6)),
                ('is_refund', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Work_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workstart_timestamp', models.DateTimeField()),
                ('workend_timestamp', models.DateTimeField()),
                ('storeowner_check', models.CharField(default='N', max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='customerrefund',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='emp',
        ),
        migrations.RemoveField(
            model_name='maintenance',
            name='store',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='orderlist',
            name='order',
        ),
        migrations.RemoveField(
            model_name='storercpt',
            name='store',
        ),
        migrations.RemoveField(
            model_name='storerefund',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='storerefund',
            name='store',
        ),
        migrations.RemoveField(
            model_name='tradelist',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='tradelist',
            name='receipt',
        ),
        migrations.RemoveField(
            model_name='worklist',
            name='emp',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='store',
        ),
        migrations.RemoveField(
            model_name='order',
            name='store',
        ),
        migrations.RemoveField(
            model_name='product',
            name='img_path',
        ),
        migrations.RemoveField(
            model_name='product',
            name='information',
        ),
        migrations.RemoveField(
            model_name='product',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='emp',
        ),
        migrations.RemoveField(
            model_name='receipt',
            name='store',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='location_code',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='store',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userId',
        ),
        migrations.AddField(
            model_name='employee',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='explain',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='picture_file_path',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier_id',
            field=models.ForeignKey(db_column='supplier_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Supplier'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Customer'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='employee_id',
            field=models.ForeignKey(db_column='employee_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Employee'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='receipt',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='display_location_code',
            field=models.DecimalField(decimal_places=0, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stock',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='uesr_id',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='contact',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='gender',
            field=models.DecimalField(decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mileage',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='daytime_hourpay',
            field=models.DecimalField(decimal_places=0, default=6800, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='fire_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nighttime_hourpay',
            field=models.DecimalField(decimal_places=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position_code',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='complete_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_timestamp',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='process_code',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='barcode',
            field=models.DecimalField(decimal_places=0, max_digits=13, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_a',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='category_b',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='supply_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_information',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='payment_method_code',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_code',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='store',
            name='store_pay',
            field=models.FloatField(),
        ),
        migrations.DeleteModel(
            name='Customerrefund',
        ),
        migrations.DeleteModel(
            name='Maintenance',
        ),
        migrations.DeleteModel(
            name='Orderlist',
        ),
        migrations.DeleteModel(
            name='Storercpt',
        ),
        migrations.DeleteModel(
            name='Storerefund',
        ),
        migrations.DeleteModel(
            name='Tradelist',
        ),
        migrations.DeleteModel(
            name='Worklist',
        ),
        migrations.AddField(
            model_name='work_list',
            name='employee_id',
            field=models.ForeignKey(db_column='employee_id', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Employee'),
        ),
        migrations.AddField(
            model_name='trade_list',
            name='barcode',
            field=models.ForeignKey(db_column='barcode', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product'),
        ),
        migrations.AddField(
            model_name='trade_list',
            name='receipt_id',
            field=models.ForeignKey(db_column='receipt_id', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Receipt'),
        ),
        migrations.AddField(
            model_name='store_refund',
            name='barcode',
            field=models.ForeignKey(db_column='barcode', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product'),
        ),
        migrations.AddField(
            model_name='store_refund',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='barcode',
            field=models.ForeignKey(db_column='barcode', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Product'),
        ),
        migrations.AddField(
            model_name='order_list',
            name='order_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Order'),
        ),
        migrations.AddField(
            model_name='maintenance_cost',
            name='employee_id',
            field=models.ForeignKey(db_column='employee_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.Employee'),
        ),
        migrations.AddField(
            model_name='maintenance_cost',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
        ),
        migrations.AddField(
            model_name='franchise_store_rcpt',
            name='store_id',
            field=models.ForeignKey(db_column='store_id', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Store'),
        ),
        migrations.AddField(
            model_name='customer_refund',
            name='trade_list_id',
            field=models.ForeignKey(db_column='trade_list_id', on_delete=django.db.models.deletion.CASCADE, to='mainapp.Trade_list'),
        ),
    ]
