# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 15:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20190607_1444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='uesr_id',
            new_name='user_id',
        ),
    ]
