# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-09 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_auto_20190608_1547'),
        ('mainapp', '0004_remove_work_list_store_id'),
    ]

    operations = [
    ]
